In [44]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/aylinggq/BCIS-321/refs/heads/main/top_100_books-2020-Aylin_Gomez_Quezada.csv')
print(df)

    Unnamed: 0  rank                           title              author  \
0          NaN     1                        Becoming      Michelle Obama
1          NaN     2            Girl, Wash Your Face       Rachel Hollis
2          NaN     3                The Wonky Donkey         Craig Smith
3          NaN     4                   Fire and Fury       Michael Wolff
4          NaN     5                            Fear        Bob Woodward
..         ...   ...                             ...                 ...
94         NaN    96               Gmorning, Gnight!  Lin-Manuel Miranda
95         NaN    97               Rich Dad Poor Dad  Robert T. Kiyosaki
96         NaN    98                   Make Your Bed  William H. McRaven
97         NaN    99  Harry Potter Paperback Box Set       J. K. Rowling
98         NaN   100  Xanathar's Guide to Everything    Wizards RPG Team

    Unnamed: 4  rating  reviews                   type  price  Unnamed: 9  \
0          NaN     4.9    13347              Hardcover  17.95         NaN
1          NaN     4.6    10521              Hardcover  13.63         NaN
2          NaN     4.7     5503              Paperback   4.99         NaN
3          NaN     4.2     9931              Hardcover  15.57         NaN
4          NaN     4.5     3220              Hardcover  15.47         NaN
..         ...     ...      ...                    ...    ...         ...
94         NaN     4.7      285              Hardcover  15.49         NaN
95         NaN     4.5     8611  Mass Market Paperback   6.45         NaN
96         NaN     4.7     2582              Hardcover  11.00         NaN
97         NaN     4.7     7742              Paperback  54.99         NaN
98         NaN     4.5      743              Hardcover  31.56         NaN

    Unnamed: 10
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
..          ...
94          NaN
95          NaN
96          NaN
97          NaN
98          NaN

[99 rows x 11 columns]

In [45]:
#Remove columns that are blank
df.drop(["Unnamed: 4"], axis=1, inplace=True)
df.drop(["Unnamed: 0"], axis=1, inplace=True)
df.drop(["Unnamed: 9"], axis=1, inplace=True)
df.drop(["Unnamed: 10"], axis=1, inplace=True)
print(df)
#Using a loop update the price of the book titled “Man’s Search for Meaning” to $9.99
df.loc[86]=[88, 'Man\'s Search for Meaning','Vicktor Frankl', 4.7, 4959, 'Paperback', 9.99]
df.head(10)

    rank                           title              author  rating  reviews  \
0      1                        Becoming      Michelle Obama     4.9    13347
1      2            Girl, Wash Your Face       Rachel Hollis     4.6    10521
2      3                The Wonky Donkey         Craig Smith     4.7     5503
3      4                   Fire and Fury       Michael Wolff     4.2     9931
4      5                            Fear        Bob Woodward     4.5     3220
..   ...                             ...                 ...     ...      ...
94    96               Gmorning, Gnight!  Lin-Manuel Miranda     4.7      285
95    97               Rich Dad Poor Dad  Robert T. Kiyosaki     4.5     8611
96    98                   Make Your Bed  William H. McRaven     4.7     2582
97    99  Harry Potter Paperback Box Set       J. K. Rowling     4.7     7742
98   100  Xanathar's Guide to Everything    Wizards RPG Team     4.5      743

                     type  price
0               Hardcover  17.95
1               Hardcover  13.63
2               Paperback   4.99
3               Hardcover  15.57
4               Hardcover  15.47
..                    ...    ...
94              Hardcover  15.49
95  Mass Market Paperback   6.45
96              Hardcover  11.00
97              Paperback  54.99
98              Hardcover  31.56

[99 rows x 7 columns]

,rank,title,author,rating,reviews,type,price
0,1,Becoming,Michelle Obama,4.9,13347,Hardcover,17.95
1,2,"Girl, Wash Your Face",Rachel Hollis,4.6,10521,Hardcover,13.63
2,3,The Wonky Donkey,Craig Smith,4.7,5503,Paperback,4.99
3,4,Fire and Fury,Michael Wolff,4.2,9931,Hardcover,15.57
4,5,Fear,Bob Woodward,4.5,3220,Hardcover,15.47
5,6,Last Week Tonight with John Oliver Presents A ...,Jill Twiss,4.9,8537,Hardcover,10.90
6,7,12 Rules for Life,Jordan B. Peterson,4.6,5067,Hardcover,15.57
7,8,Magnolia Table,Joanna Gaines,4.7,1964,Hardcover,18.27
8,9,Whose Boat Is This Boat?,The Staff of The Late Show with,4.5,2509,Hardcover,6.66
9,10,The Subtle Art of Not Giving a F*ck,Mark Manson,4.4,5455,Hardcover,14.99

In [46]:
#Using a loop make sure the type field is either Hardcover or Paperback (convert Board Book to Hardcover and Mass Market Paperback to Paperback)
changed = 0
i = 0
for t in df.type:
  if t == 'Board Book':
    df.type.replace('Board Book', 'Hardcover', inplace=True)
    changed +=1
  if t == 'Mass Market Paperback':
    df.type.replace('Mass Market Paperback', 'Paperback', inplace=True)
    changed +=1
print(changed)
df.head()

1

/tmp/ipykernel_11203/2899139706.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.type.replace('Mass Market Paperback', 'Paperback', inplace=True)

,rank,title,author,rating,reviews,type,price
0,1,Becoming,Michelle Obama,4.9,13347,Hardcover,17.95
1,2,"Girl, Wash Your Face",Rachel Hollis,4.6,10521,Hardcover,13.63
2,3,The Wonky Donkey,Craig Smith,4.7,5503,Paperback,4.99
3,4,Fire and Fury,Michael Wolff,4.2,9931,Hardcover,15.57
4,5,Fear,Bob Woodward,4.5,3220,Hardcover,15.47

In [47]:
#Using a loop create a new calculated field representing rating/price (that is the rating divided by the price rounded to two decimal
#places e.g. 4.2 / 15.57 = 0.27). Create this field, call it “rating_by_price”, and add it to the DataFrame as the fifth column (on the right-hand side of rating)
rating = df['rating']
price = df['price']
rating_by_price = rating/price
print(rating_by_price)
df.insert(4, 'rating_by_price', rating_by_price)
df.sort_values(by=['rating_by_price'], ascending=False)
df.head()

0     0.272981
1     0.337491
2     0.941884
3     0.269750
4     0.290886
        ...
94    0.303422
95    0.697674
96    0.427273
97    0.085470
98    0.142586
Length: 99, dtype: float64

,rank,title,author,rating,rating_by_price,reviews,type,price
0,1,Becoming,Michelle Obama,4.9,0.272981,13347,Hardcover,17.95
1,2,"Girl, Wash Your Face",Rachel Hollis,4.6,0.337491,10521,Hardcover,13.63
2,3,The Wonky Donkey,Craig Smith,4.7,0.941884,5503,Paperback,4.99
3,4,Fire and Fury,Michael Wolff,4.2,0.269750,9931,Hardcover,15.57
4,5,Fear,Bob Woodward,4.5,0.290886,3220,Hardcover,15.47

In [51]:
#Write your updated DataFrame to a new CSV file called “{Your_Name}_top_100_books_cleaned.csv”
df.to_csv('Aylin_Gomez_top_100_books_2020_cleaned.csv')